# Generated by Django 5.2.6 on 2025-11-19 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='用户标识', max_length=100)),
                ('title', models.CharField(default='新对话', help_text='会话标题', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='用户标识', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='用户名称', max_length=100, null=True)),
                ('preferences', models.JSONField(default=dict, help_text='用户偏好设置')),
                ('key_points', models.TextField(blank=True, help_text='记忆要点', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', '助手'), ('tool', '工具')], help_text='消息角色', max_length=20)),
                ('content', models.TextField(help_text='消息内容')),
                ('message_id', models.CharField(blank=True, help_text='消息唯一标识', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('metadata', models.JSONField(blank=True, help_text='额外元数据', null=True)),
                ('conversation', models.ForeignKey(help_text='所属会话', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
