# Generated by Django 5.2.6 on 2025-11-26 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_userchatprofile_preferences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='事项标题', max_length=200)),
                ('description', models.TextField(blank=True, help_text='事项描述', null=True)),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='in_progress', help_text='事项状态', max_length=20)),
                ('long_term_memory', models.TextField(blank=True, help_text='长期记忆，格式：时间:事件描述;时间:事件描述;', null=True)),
                ('last_memory_update', models.DateTimeField(auto_now_add=True, help_text='最后记忆更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('user', models.ForeignKey(help_text='关联用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='关联事项', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chat.issue'),
        ),
    ]
