# Generated by Django 5.2.6 on 2025-12-05 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatmessage_conversation_chatmessage_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='知识库名称', max_length=200)),
                ('description', models.TextField(blank=True, help_text='知识库描述', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('issue', models.OneToOneField(help_text='关联事项', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='chat.issue')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文档标题', max_length=200)),
                ('content', models.TextField(help_text='文档内容')),
                ('file_name', models.CharField(blank=True, help_text='文件名', max_length=200, null=True)),
                ('file_type', models.CharField(blank=True, help_text='文件类型', max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, help_text='文件大小（字节）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('knowledge_base', models.ForeignKey(help_text='关联知识库', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chat.knowledgebase')),
            ],
        ),
    ]
