# Generated by Django 5.2.6 on 2025-11-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userchatprofile_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatprofile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='userchatprofile',
            name='assistant_name',
            field=models.CharField(default='助手', help_text='助手名称', max_length=10),
        ),
        migrations.AddField(
            model_name='userchatprofile',
            name='extra_notice',
            field=models.CharField(blank=True, help_text='注意事项', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userchatprofile',
            name='style',
            field=models.CharField(default='general', help_text='聊天风格', max_length=20),
        ),
    ]
