# Generated by Django 5.2.6 on 2025-11-27 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_issue_conversation_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='关联事项', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chat.issue'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(help_text='关联用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
