# Generated by Django 5.2.6 on 2025-11-19 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='用户名', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='邮箱地址', max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='手机号码', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, help_text='名字', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text='姓氏', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('is_staff', models.BooleanField(default=False, help_text='是否为管理员')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='注册时间')),
                ('last_login', models.DateTimeField(blank=True, help_text='最后登录时间', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '浅色主题'), ('dark', '深色主题')], default='light', help_text='界面主题', max_length=20)),
                ('language', models.CharField(choices=[('zh-cn', '简体中文'), ('en-us', '英文')], default='zh-cn', help_text='语言偏好', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='是否启用通知')),
                ('email_notifications', models.BooleanField(default=True, help_text='是否启用邮件通知')),
                ('auto_save', models.BooleanField(default=True, help_text='是否自动保存')),
                ('other_settings', models.JSONField(default=dict, help_text='其他设置')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('user', models.OneToOneField(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='头像', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='个人简介', null=True)),
                ('company', models.CharField(blank=True, help_text='公司', max_length=200, null=True)),
                ('position', models.CharField(blank=True, help_text='职位', max_length=200, null=True)),
                ('website', models.URLField(blank=True, help_text='个人网站', null=True)),
                ('location', models.CharField(blank=True, help_text='所在地', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('user', models.OneToOneField(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
